### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by LolIOSx9** [MJx0/iOS_UE4Dumper#2]
Compiling Tweak/includes/SSZipArchive/minizip/mz_strm_zlib.c (arm64)…
Tweak/includes/SSZipArchive/minizip/mz_strm_zlib.c:138:14: error: variable 'total_in' set but not used [-Werror,-Wunused-but-set-variable]
    uint32_t total_in = 0;

**Comment by saudgl** [comment]
I have the same problem !!

**Comment by MJx0** [comment]
@LolIOSx9 @saudgl you can remove the unused variable or just suppress the warning in makefile cflags/ccflags
-Wno-error=unused-but-set-variable or -w to suppress all warnings
