### ISSUE TITLE
can i compile it with xcode? on theos rootless I get a compile failed error

### ISSUE THREAD

**Issue by minhquangxx** [MJx0/iOS_UE4Dumper#22]
can i compile it with xcode? on theos rootless I get a compile failed error

**Comment by MJx0** [comment]
what error do you get?

**Comment by minhquangxx** [comment]
https://scontent.fdad3-1.fna.fbcdn.net/v/t1.15752-9/384557885_1057465235277125_6965639936346114531_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=8cd0a2&_nc_ohc=IvCa3WrfB6wAX-d7i7h&_nc_ht=scontent.fdad3-1.fna&oh=03_AdQTKvPLWpG2dxPEt9X4vsrSPrUu021QmlQ2w7TG74YloQ&oe=6571873E

I have the error as shown in the picture, previous versions did not error

**Comment by MJx0** [comment]
Maybe you didn't clone the submodules?
Try 
```
git clone --recursive https://github.com/MJx0/iOS_UE4Dumper.git
```

**Comment by minhquangxx** [comment]
Thanks bro, this working ❤️❤️

**Comment by minhquangxx** [comment]
![950D8FF9-5030-49C8-89B2-F500BCEFE67B](https://github.com/MJx0/iOS_UE4Dumper/assets/40761942/a755fda8-47f1-4bf4-bc25-c301511afe51)
Can’t make package rootless, how to fix bro

**Comment by minhquangxx** [comment]
![1E8E2463-8AF6-4396-85CE-A48F19260D45](https://github.com/MJx0/iOS_UE4Dumper/assets/40761942/7fc102ce-c044-461f-81af-225bda485300)

**Comment by MJx0** [comment]
How did you install theos on your device? could be an issue with installation

**Comment by minhquangxx** [comment]
Am follow iosgods install theos rootless

**Comment by MJx0** [comment]
I can't reproduce this error on my end. By the way why are you using root to compile the project? Did you perhaps also install theos with root? The instructions say to install theos as normal user (mobile) not root

**Comment by Leeksov** [comment]
what sdk you use?
