### ISSUE TITLE
Farlight 84 sig scan offsets broken

### ISSUE THREAD

**Issue by silentninjabee** [MJx0/iOS_UE4Dumper#23]
Farlight 84 ObjObjects offset signature is broken with latest game update v15.1.2

These two signatures both work from v15 to the latest patch of the game  v15.1.2 if anyone else is having problem u can update the signature using one of these:

```
Ida Sig ObjectsPtr = "2A 7D ? 13 ? ? ? 12 08 01 09 4B 29 ? ? ? 1F 20 03 D5 29 ? ? ? 29 ? ? F8";
ObjectsPtr += 0xC;

Ida Sig ObjectsPtr = "29 3D 10 12 08 01 09 4B ? ? ? ? 29 D9 6A F8 08 25 3A 9B 08 ? ? 39 88 ? ? 37";
ObjectsPtr += 0x8;
```

**Comment by MJx0** [comment]
Thanks, I have uploaded new release with this fix.
