### ISSUE TITLE
Request to add new support

### ISSUE THREAD

**Issue by Lotus0915** [MJx0/iOS_UE4Dumper#29]
Hello, can you add a new package name to the configuration folder of PUBG2 and re -pack them? The new bag is: com.tencent.tmgp.pubgmhd, thank you very much

**Comment by MJx0** [comment]
okay

**Comment by Lotus0915** [comment]
thanks!!

**Comment by MJx0** [comment]
added

**Comment by Lotus0915** [comment]
Thank you very much！
