### ISSUE TITLE
(CODM - Call of duty mobile) support UE4 ios

### ISSUE THREAD

**Issue by columbusux** [MJx0/iOS_UE4Dumper#37]
I have one year wait for codm ios mobile tool to dump class and headers but unfortunately I have no idea what is the issue with it in case its can be dumped in android but in ios no one make it work its like dream , pls if you can add it i will send you decrypt ipa site that u can get it in so you can test , and i will show some github issue in another case in the same subject to be clear and thank you for ur hard work…

[Decrypted CODM](https://decrypt.day/app/id1287282214)

[old github issue](https://github.com/djkaty/Il2CppInspector/issues/218)

[Another unsolved GitHub issue](https://github.com/Perfare/Il2CppDumper/issues/734)

**Comment by StevenLyo** [comment]
pls forgive my impolite laughter😂
