### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by Chensem** [MJx0/iOS_UE4Dumper#5]
Hello , Thank for your project . i am learning from your awesome project , but i have some questions below .
Ark game using ue4 version 4.17 , i can use your tool to dump the sdk successfully . but i don't know how to find the pattern , i do the operation below .
1. first i download the game 
2. the dumped the game and load the main binary to ida
3. use the pattern to search the offset , can search it successfully 
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/27469499/182314089-9265d8f0-c95d-4fd9-96a5-b7b969f7823f.png">
4. but if i am in black box , i can't find the pattern , because i can't find the specific strings like "duplicate harded name" , so i can't detect the offset of GUObjectArrayPtr and GNamePtr
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/27469499/182314358-46a24d16-b28d-49e1-89e0-5c9cc6209096.png">

so i want to know how to detect the pattern . waiting for your reply

**Comment by MJx0** [comment]
@Chensem Unreal engine is open source. You can download the version you want and search for another string reference that may exist. There are many other references you can look for.

**Comment by Chensem** [comment]
thanks
