### ISSUE TITLE
How To Detect Offset

### ISSUE THREAD

**Issue by Chensem** [MJx0/iOS_UE4Dumper#6]
Hello , I have some new questions about offset 
I encounter a game use ue4 with version 4.26 that can't dump with your tool .
i think maybe the offset differ with ue4.25 .
so i wan't to know whether there's a way to calculate the offset quickly ?

<img width="795" alt="image" src="https://user-images.githubusercontent.com/27469499/182879460-4cbd1b1e-86f5-43be-b2f3-198001b0f131.png">
i can't understand the offset why is 0xd0 , as usually is 0x10 , just like the struct as below .
<img width="944" alt="image" src="https://user-images.githubusercontent.com/27469499/182879933-65827ac6-cfba-40f1-bdf2-e4703467fc10.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/27469499/182880074-b9d4cd0b-e0e9-4261-921b-a580607d50eb.png">

**Comment by MJx0** [comment]
@Chensem Because the namepool pointer you can find doesn't point directly to FNameEntryAllocator. Find any function that uses the blocks variable like FNamePool::Resolve and confirm the blocks offset. In my case i found blocks usually at +0xd0 so FNameEntryAllocator must be at +0xc0 from the pointer.

**Comment by Chensem** [comment]
Oh , I compile the source code , then use ida to analyze the offset . 

Thank For Your Reply . 

^ ^ ~

**Comment by Ducmanhvn** [comment]
> Oh , I compile the source code , then use ida to analyze the offset .
> 
> Thank For Your Reply .
> 
> ^ ^ ~

Hi bro can you help me complete the source i got so much error
