### ISSUE TITLE
GNU Make 3.81 error:set but not used

### ISSUE THREAD

**Issue by fsleo** [MJx0/iOS_UE4Dumper#8]
macOS Monterey V12.6 (M2) GNU Make 3.81

Tweak/includes/SSZipArchive/minizip/mz_strm_zlib.c:138:14: error: variable 'total_in' set but not used [-Werror,-Wunused-but-set-variable]
    uint32_t total_in = 0;

**Comment by Ducmanhvn** [comment]
Did you fix that i still stuck at rebuid the file
